name: Build main branch

on:
  push:
    branch:
      - main
    tags-ignore:
      - 'v*'
  workflow_dispatch:


jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            artifact_name: ssd-flash-id_amd64
          - target: aarch64-unknown-linux-gnu
            artifact_name: ssd-flash-id_arm64
          # - target: x86_64-unknown-linux-musl
          #   artifact_name: ssd-flash-id_amd64-musl
          # - target: aarch64-unknown-linux-musl
          #   artifact_name: ssd-flash-id_arm64-musl
    
    steps:
      - name: Debug Context
        run: echo '${{ toJson(github) }}'
      - name: Checkout Current Repo (Metadata)
        uses: actions/checkout@v4
        with:
          #fetch-tags: true
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Fetch Metadata from Tag
        id: get_ref
        run: |
          TARGET_REF=$(cat ./ref)

          if [ -z "$TARGET_REF" ]; then
            echo "错误: 未在标签描述中找到 'ref: <sha>'"
            exit 2026
          fi
          echo "DEBUG TARGET_REF=${TARGET_REF}"
          echo "target_ref=$TARGET_REF" >> $GITHUB_OUTPUT



      - name: Checkout Target Repo
        uses: actions/checkout@v4
        with:
          repository: pseudolabel/ssd-flash-id
          path: external_source
          ref: ${{ steps.parse_tag.outputs.target_ref }}
          fetch-depth: 1

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
          
      - name: Install Cross
        run: cargo install cross
        
      - name: Compile Release
        working-directory: external_source
        run: cross build --target ${{ matrix.target }} --release

